nrp:
  hosts:
    nrp001:
      ansible_host: 10.100.100.5
      fortios_access_token: mzkfxdjN0pcr3mkpHpr9f5nh14ywx3
      lan: "172.16.212.0/26"
      lan_gw: "172.16.212.1"
      store: 001
    nrp003:
      ansible_host: 10.100.100.2
      fortios_access_token: cHnw7hkHy8q9G7x64w1sHqqb8nkcqq
      lan: "172.16.212.192/26"
      lan_gw: "172.16.212.193"
      store: 003
  vars:
    clientID: "nrp"
    ddc_vlan: "172.28.0.40/29"
    cynergi_server: "172.28.0.42" 
    vdom: "root"
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_network_os: fortinet.fortios.fortios
    pksecret: "hi23tou78ch09inc"
prod:
  children:
    nrp:
