#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/rtoConfig
- name: get interface info
  fortinet.fortios.fortios_configuration_fact: 
    access_token: "{{ fortios_access_token }}"
    formatters:
      - name
      - ip
    selector: 'system_interface'
  register: interface_facts

- name: set fact
  set_fact:
    serial: "{{interface_facts.meta.serial}}"

- name: show facts 
  ansible.builtin.debug:
    msg: "{{interface_facts.meta.serial}}"

- name: remove default internal policy 
  fortinet.fortios.fortios_firewall_policy:
    access_token: "{{ fortios_access_token }}"
    state: "absent"
    firewall_policy:
      policyid: "1"

- name: remove guest wifi policy 
  fortinet.fortios.fortios_firewall_policy:
    access_token: "{{ fortios_access_token }}"
    state: "absent"
    firewall_policy:
      policyid: "2"
  when: serial is search("FWF40") or serial is search("FWF60")

- name: remove internal object
  fortinet.fortios.fortios_firewall_address:
    state: "absent"
    access_token: "{{ fortios_access_token }}"
    firewall_address:
      name: "internal"

- name: remove DHCP
  fortinet.fortios.fortios_system_dhcp_server:
    state: "absent"
    access_token: "{{ fortios_access_token }}"
    system_dhcp_server:
      id: "{{item.id}}"
  with_items: "{{dhcpServers}}"

- name: remove fortilink from 
  fortinet.fortios.fortios_system_ntp:
    access_token: "{{ fortios_access_token }}"
    system_ntp:
      server_mode: "disable"

- name: remove wifi from internal
  fortinet.fortios.fortios_system_switch_interface:
    state: "present"
    access_token: "{{ fortios_access_token }}"
    system_switch_interface:
      name: "{{ (interface_facts.meta.results | selectattr('ip', 'search', '192.168.1.99 255.255.255.0') | list | first).name }}"
      member: 
        - interface_name: "lan"
#      ip: "{{lan}}"

- name: remove fortilink
  fortinet.fortios.fortios_system_interface:
    state: "absent"
    access_token: "{{ fortios_access_token }}"
    system_interface:
      name: "fortilink"

#create address objects
- name: vpn address objects
  fortinet.fortios.fortios_firewall_address:
    state: "present"
    access_token: "{{ fortios_access_token }}"
    firewall_address:
      name: "{{item.name}}"
      type: "{{item.type}}"
      subnet: "{{item.address}}"
      allow_routing: "enable"
  with_items: "{{addrObject}}"

#create address groups
- name: address groups
  fortinet.fortios.fortios_firewall_addrgrp:
    state: "present"
    access_token: "{{ fortios_access_token }}"
    firewall_addrgrp:
      name: "{{item.name}}"
      member: 
        - name: "{{item.member}}"
  with_items: "{{addrGrp}}"

- name: initial sdwan non wifi
  fortinet.fortios.fortios_system_sdwan:
    access_token: "{{ fortios_access_token }}"
    system_sdwan:
      members:
        -
          seq_num: "0"
          interface: "a"
          cost: "5"
        -
          seq_num: "0"
          interface: "wan"
  when: serial is search("FWF40") or serial is search("FGT40")

- name: initial sdwan wifi
  fortinet.fortios.fortios_system_sdwan:
    access_token: "{{ fortios_access_token }}"
    system_sdwan:
      members:
        -
          seq_num: "0"
          interface: "wan2"
          cost: "5"
        -
          seq_num: "0"
          interface: "dmz"
  when: serial is search("FWF60") or serial is search("FGT60")

- name: VPN phase 1 main 40 series
  fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
    state: "present"
    access_token: "{{ fortios_access_token }}"
    vpn_ipsec_phase1_interface:
      name: "{{item.name}}"
      type: "static"
      remote_gw: "{{item.remote_gw}}"
      interface: "wan"
      keylife: "28800"
      mode: "aggressive"
      peertype: "one"
      net_device: "disable"
      proposal: "aes256-sha1"
      localid: "{{clientID}}{{store}}-rto"
      dpd: "on-idle"
      dhgrp: "2"
      peerid: "{{item.peerid}}"
      psksecret: "{{pksecret}}"
      dpd_retryinterval: "60"
  with_items: "{{vpnPhase1Main}}"
  when: serial is search("FWF40") or serial is search("FGT40")

- name: VPN phase 1 main 60 series
  fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
    state: "present"
    access_token: "{{ fortios_access_token }}"
    vpn_ipsec_phase1_interface:
      name: "{{item.name}}"
      type: "static"
      remote_gw: "{{item.remote_gw}}"
      interface: "wan1"
      keylife: "28800"
      mode: "aggressive"
      peertype: "one"
      net_device: "disable"
      proposal: "aes256-sha1"
      localid: "{{clientID}}{{store}}-rto"
      dpd: "on-idle"
      dhgrp: "2"
      peerid: "{{item.peerid}}"
      psksecret: "{{pksecret}}"
      dpd_retryinterval: "60"
  with_items: "{{vpnPhase1Main}}"
  when: serial is search("FWF60") or serial is search("FGT60")

- name: VPN phase 1 failover 40 series
  fortinet.fortios.fortios_vpn_ipsec_phase1_interface:
    state: "present"
    access_token: "{{ fortios_access_token }}"
    vpn_ipsec_phase1_interface:
      name: "{{item.name}}"
      type: "static"
      remote_gw: "{{item.remote_gw}}"
      interface: "a"
      keylife: "28800"
      mode: "aggressive"
      peertype: "one"
      net_device: "disable"
      proposal: "aes256-sha1"
      localid: "{{clientID}}{{store}}-rto"
      dpd: "on-idle"
      dhgrp: "2"
      peerid: "{{item.peerid}}"
      psksecret: "{{pksecret}}"
      dpd_retryinterval: "60"
  with_items: "{{vpnPhase1Failover}}"
  when: serial is search("FWF40") or serial is search("FGT40")

- name: VPN phase 2 
  fortinet.fortios.fortios_vpn_ipsec_phase2_interface:
    state: "present"
    access_token: "{{ fortios_access_token }}"
    vpn_ipsec_phase2_interface:
      name: "{{item.name}}"
      phase1name: "{{item.phase1}}"
      proposal: "aes256-sha1"
      pfs: "disable"
      keepalive: "enable"
      src_addr_type: "name"
      dst_addr_type: "name"
      src_name: "{{item.source}}"
      dst_name: "{{item.remote}}"
      keylifeseconds: "28800"
  with_items: "{{vpnPhase2}}"

- name: sdwan 40 Series
  fortinet.fortios.fortios_system_sdwan:
  state: "present"
  access_token: "{{ fortios_access_token }}"
  system_sdwan:

- name: Firewall Policies
  fortios_firewall_policy:
    access_token: "{{ fortios_access_token }}"
    state: "present"
    firewall_policy:
      policyid: "0"
      name: "{{item.name}}"
      srcintf:
      -
        name: "{{item.srcint}}"
      dstintf:
      -
        name: "{{item.dstint}}"
      srcaddr:
      -
        name: "{{item.srcaddr}}"
      dstaddr:
      -
        name: "{{item.dstaddr}}"
      action: "accept"
      schedule: "always"
      service:
      -
        name: "ALL"
      nat: "{{item.nat}}"